version: '3.3'

services:
  nvidia-flask:
    build: ./app
    # network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
    volumes:
      - ./app:/usr/src/app
      - .:/user/src
    ports:
      - 80:9999
    environment:
      - "PYTHONUNBUFFERED=1"
    links:
        - mongodb
    depends_on:
        - mongodb


  mongodb:
    image: mongo:latest
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: deep_fish
      # MONGO_INITDB_ROOT_PASSWORD: barscht123
    ports:
        - 27017:27017
    volumes:
      - ../../fish_counter_data/mongo_data:/data/db
    command: --quiet
